class FormsPage:
    firstName_input = "firstName"
    lastName_input = "lastName"
    userEmail_input = "userEmail"
    gender_radio_male = "//label[@for='gender-radio-1']"
    gender_radio_female = "//label[@for='gender-radio-2']"
    gender_radio_other = "//label[@for='gender-radio-3']"
    userNumber_input = "userNumber"
    dateOfBirthInput_input = "dateOfBirthInput"
    subjectsInput_input = "#subjectsInput"
    hobbies_checkbox_sports_input = "hobbies-checkbox-1"
    hobbies_checkbox_reading_input = "hobbies-checkbox-2"
    hobbies_checkbox_music_input = "hobbies-checkbox-3"
    uploadPicture_button = "uploadPicture"
    currentAddress_input = "currentAddress"
    stateSelect_input = "state"
    citySelect_input = "city"
    submitButton_input = "submit"
