class FormsPage:
    firstName_input = "firstName"
    lastName_input = "lastName"
    userEmail_input = "userEmail"
    gender_radio_male = "//*[@id=\"genterWrapper\"]/div[2]/div[1]/label"#"gender-radio-1"
    gender_radio_female = "//*[@id='genterWrapper']/div[2]/div[2]"#"gender-radio-2"
    gender_radio_other = "//*[@id='genterWrapper']/div[2]/div[3]"
    userNumber_input = "userNumber"
    dateOfBirthInput_input = "dateOfBirthInput"
    subjectsInput_input = "#subjectsInput"
    hobbies_checkbox_sports_input = "hobbies-checkbox-1"
    hobbies_checkbox_reading_input = "hobbies-checkbox-2"
    hobbies_checkbox_music_input = "hobbies-checkbox-3"
    uploadPicture_button = "uploadPicture"
    currentAddress_input = "currentAddress"
    stateSelect_input = "state"
    citySelect_input = "city"
    submitButton_input = "submit"
